export const corporateMembers = [
    { id: 1, designation: "Director", institution: "National Institute of Technology, (Formerly, REC), Warangal" },
    { id: 2, designation: "Vice-Chancellor", institution: "Padmavathi Mahila Visvavidyalayam, Tirupathi" },
    { id: 3, designation: "Principal", institution: "H. R. D. Degree and P. G. College, Narayanaguda, Hyderabad" },
    { id: 4, designation: "Principal", institution: "New Noble Degree & P. G.College, Gaddiannaram ‘X’ Roads, Dilsukhnagar, Hyderabad" },
    { id: 5, designation: "Principal", institution: "The Ideal Junior College, Dilsukhnagar, Hyderabad" },
    { id: 6, designation: "Principal", institution: "Sri. Sai Junior, Degree &P. G. College, Sivaganga Theatre Road, Dilsukhnagar, Hyderabad" },
    { id: 7, designation: "Principal", institution: "Jagruthi Degree and P. G. College, Padmashali Bhavan, Narayanaguda, Hyderabad" },
    { id: 8, designation: "Principal", institution: "C. V. L. N. R. Degree College, Anantapur" },
    { id: 9, designation: "Principal", institution: "St. Joseph’s College, Sunkasala Road, Kurnool" },
    { id: 10, designation: "Principal", institution: "Vasavi Mahila Kalasala, 53/40. Near King Market, Kurnool" },
    { id: 11, designation: "Principal", institution: "S. V. Degree College, Kadapa" },
    { id: 12, designation: "Principal", institution: "Nagarjuna Degree College for Women, Near R. T. C Bus-stand, Kadapa" },
    { id: 13, designation: "Principal", institution: "Vagdevi Degree College, Y. M. R. Colony, Proddutur, Kurnool Dt" },
    { id: 14, designation: "Principal", institution: "Dr. Agarala Eswara Reddy College, Reddy & Reddy colony, Tirupati" },
    { id: 15, designation: "Principal", institution: "Rao’s Degree College, Nellore" },
    { id: 16, designation: "Principal", institution: "Krishna Chaithanya Degree College, Ananthapur" },
    { id: 17, designation: "Principal", institution: "S. B. N. Degree College, Ananthapur" },
    { id: 18, designation: "Principal", institution: "V. Degree College, Sai Nagar, Ananthapur" },
    { id: 19, designation: "Principal", institution: "Sri Sai Degree College, Raj Towers, Ananthpur" },
    { id: 20, designation: "Principal", institution: "Smt.& Sri. R. S. Janardana Degree College for Women, Sankarapuram, Cuddapah" },
    { id: 21, designation: "Principal", institution: "Vignana Sudha Degree College, Chittor" },
    { id: 22, designation: "Principal", institution: "Shri. Gnanambica Degree College, Madanapalli" },
    { id: 23, designation: "Principal", institution: "Sri. Varadharaja P. G. College, Proddutur" },
    { id: 24, designation: "Principal", institution: "Rajiv Gandhi Institute of P.G. Studies, Sarpavaram Junction, Kakinada (E.G. Dist.)" },
    { id: 25, designation: "Sri N. Rama Rao", institution: "Secretary & Correspondent, Sri Subbaraya & Narayana College, Narsaraopet" },
    { id: 26, designation: "Director", institution: "IICT, Tarnaka, Secunderabad" },
    { id: 27, designation: "Principal", institution: "Hindu College, P.G. Courses, Guntur" },
    { id: 28, designation: "The Principal", institution: "V.S.Lakshmi Womens Degree College, Kakinada" },
    { id: 29, designation: "The Principal", institution: "Aditya Degree College, Santhi Nagar, Kakinada" },
    { id: 30, designation: "The Principal", institution: "S.V.K.P and Dr.K.S.Raju Arts and Science College, Penugonda, W.G.D.T." },
    { id: 31, designation: "The Principal", institution: "S.K.Degree College (P.G. Courses), Ayyannapeta Junction, Vijayanagaram" },
    { id: 32, designation: "Director", institution: "Sri Y.N.College (PG courses), Narasapur-534260, WGDT" },
    { id: 33, designation: "Director", institution: "BBCIT, Kacheguda, Hyderabad" },
    { id: 34, designation: "Secretary and Correspondent", institution: "CBIT, Gandipet, Hyderabad" },
    { id: 35, designation: "Secretary", institution: "Vaagdevi Degree and PG College, Hanamkonda" },
    { id: 36, designation: "Head", institution: "Dept. of Mathematics, Osmania University, Hyderabad" },
    { id: 37, designation: "Kakinada Institute of Engineering and Technology", institution: "Yanam Road, Korangi, Kakinada" },
    { id: 38, designation: "Malla Reddy Engineering College", institution: "Maisamma Guda, Medchal, Secunderabad" },
    { id: 39, designation: "Head", institution: "Dept. of Mathematics, Dadi Institute of Engineering & Technology (DIET), Anakapalle, Visakhapatnam" },
    { id: 41, designation: "Head", institution: "Dept. of Mathematics, Jyothishmathi Institute of Technology and Science, Nustulapur, Karimnagar – 505 481" },
    { id: 42, designation: "Registrar", institution: "Dept. Of Mathematics, Adikavi Nannaya University, D.No. 25-7-9/1, Jaya Krishna Puram, Rajahmundry" },
    { id: 43, designation: "Principal", institution: "Malla Reddy Inst of Tech & Science, Maisamma Guda, Dhulapally, Secunderabad" },
    { id: 44, designation: "Principal", institution: "CM Engg College, Maisamma Guda, Dhulapally, Secunderabad" },
    { id: 45, designation: "Principal", institution: "Joginapally B.R.Engg College, Yenkapally (Village), Moinabad(Mdl), R.R.Dist." },
    { id: 46, designation: "Dept. of Mathematics", institution: "S.V. University, TIRUPATI" },
    { id: 47, designation: "Anurag group of institutions", institution: "Venkatapur (Village), Ghatkesar (Mandal), Ranga Reddy (Dist)" },
    { id: 48, designation: "Geethanjali College of Engineering and Technology", institution: "Sy.No.33 and 34, Cheeryal village, Keesara Mandal, Ranga Reddy Dist. A.P. 501 301" },
  ];
  